const userSeeds = [
  {
    name: "Ahmet Yılmaz",
    email: "ahmet@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Mehmet Kaya",
    email: "mehmet@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Ayşe Demir",
    email: "ayse@gmail.com",
    password: "123456",
    role: "admin",
    createdAt: new Date(),
  },
  {
    name: "Fatma Çelik",
    email: "fatma@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Ali Şahin",
    email: "ali@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Zeynep Arslan",
    email: "zeynep@gmail.com",
    password: "123456",
    role: "superUser",
    createdAt: new Date(),
  },
  {
    name: "Mustafa Koç",
    email: "mustafa@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Elif Aydın",
    email: "elif@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Hasan Güneş",
    email: "hasan@gmail.com",
    password: "123456",
    role: "admin",
    createdAt: new Date(),
  },
  {
    name: "Merve Polat",
    email: "merve@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Burak Erdoğan",
    email: "burak@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Selin Öztürk",
    email: "selin@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Emre Doğan",
    email: "emre@gmail.com",
    password: "123456",
    role: "superUser",
    createdAt: new Date(),
  },
  {
    name: "Büşra Yıldız",
    email: "busra@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Tolga Çetin",
    email: "tolga@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Cansu Kılıç",
    email: "cansu@gmail.com",
    password: "123456",
    role: "admin",
    createdAt: new Date(),
  },
  {
    name: "Oğuzhan Aktaş",
    email: "oguzhan@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Derya Bulut",
    email: "derya@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Serkan Avcı",
    email: "serkan@gmail.com",
    password: "123456",
    role: "user",
    createdAt: new Date(),
  },
  {
    name: "Pınar Özdemir",
    email: "pinar@gmail.com",
    password: "123456",
    role: "superUser",
    createdAt: new Date(),
  },
];

module.exports = userSeeds;
